name: Basic Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "✅ This workflow ran because a Pull Request was created or updated for the main branch."
